pub mod document_handler;
pub mod document_issue;
pub mod document_node;
pub mod insert_position;
pub mod output_format;
pub mod path_aliases;
pub mod path_range;
pub mod path_segment;
pub mod selector;
pub mod text_map;
pub mod validation_error;

pub use document_handler::{DocumentHandler, HandlerError};
pub use document_issue::{DocumentIssue, IssueSeverity};
pub use document_node::DocumentNode;
pub use insert_position::InsertPosition;
pub use output_format::{BinaryInfo, OutputFormat, RawOptions, ViewOptions};
pub use path_aliases::PathAliases;
pub use path_range::{parse_range_paths, PathRangeSegment};
pub use path_segment::PathSegment;
pub use selector::Selector;
pub use text_map::{BBoxSpan, OffsetSpan, StyleSpan, TextMapMeta, TextOffsetMap};
pub use validation_error::ValidationError;
